### ISSUE TITLE
i cant get the cells.json text to stay in the index.html file

### ISSUE THREAD

**Issue by BousClan** [the1killer/sm_overview#1]
i have tried about 5 times now to copy the cells.json text into the index.html file all goes well and saves until I try to open the .HTML file and then it resets the file removing the cells text from the script

**Comment by BousClan** [comment]
i am using notepad ++ if that matters

**Comment by the1killer** [comment]
Make sure you have extracted the zip file? If you are editing a temp file in the zip maybe that's how its losing changes?

**Comment by BousClan** [comment]
that worked thank you
