### ISSUE TITLE
Cells.json not being created

### ISSUE THREAD

**Issue by GandalftheGreyt3719** [the1killer/sm_overview#13]
I follow the instructions in the video guide, and after I start the game, going into the world I want, and then checking the survival folder, it doesnt create the cells.json folder. I check indentation, and tried just replacing the vanilla terrain file with the one supplied and it didnt work either.
Could it have something to do with the new line between the UpdateLocationStorage() and return true lines?

**Comment by the1killer** [comment]
There is also a 2nd file to edit now, did you edit tile_database.lua?

**Comment by JigglePiggle** [comment]
@GandalftheGreyt3719 I was having the same issues, i managed to fix it by just dragging and dropping all 3 lua files to their respective place is the sm file path including SurvivalGame.lua.
hope this helps!

**Comment by GandalftheGreyt3719** [comment]
Ok. I will try that next time im on that computer.

Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by paucc** [comment]
@JigglePiggle Thank you very much, this helped me a lot. I was also stuck because I didn't replace the `SurvivalGame.lua` and the `Cells.json` file wasn't created.

:raised_hands:
