### ISSUE TITLE
No cells.json

### ISSUE THREAD

**Issue by RadGH** [the1killer/sm_overview#2]
Hey great looking tool! I am trying to get it to work for my game but there is no cells.json in the folder "\steamapps\common\Scrap Mechanic\Survival\". I searched the entire Scrap Mechanic directory and there is no cells.json at all.

I created a world in Survival, assume it should have been generated? I'm new to the game though, so maybe I'm missing a step.

![explorer_2021-01-10_16-19-03](https://user-images.githubusercontent.com/2008464/104139332-93b45680-535f-11eb-94c4-a5389416cc9c.png)

Any idea what I need to do? Thanks!

**Comment by the1killer** [comment]
Did you copy the code over in the terrain_overworld.lua inside the Scripts folder there? Then all you should have to do is load your save file and should output cells.json in that directory.

**Comment by RadGH** [comment]
Oh yeah I skipped the step to load the save game. Whoops! Thanks I'll give that a shot :)
