### ISSUE TITLE
Error while loading cells.json

### ISSUE THREAD

**Issue by kendallroth** [the1killer/sm_overview#9]
Successfully generated a `cells.json` but when I tried to load it in the web viewer, was presented with a console error (and blank map).

```
./assets/json/cells.json had a problem loading. Sorry!
```

[cells.json.txt](https://github.com/the1killer/sm_overview/files/7776223/cells.json.txt)

**Comment by the1killer** [comment]
Are you loading it locally? If so you have to follow the directions in the readme for pasting the contents of cell.json into the JavaScript file.

**Comment by kendallroth** [comment]
@the1killer You have no idea how absolutely apologetic I am about this...as a developer, "failing to read the manual" is one of my pet peeves and I am so sorry to have fallen prey to it in this case 🤦. Excellent tool, 100% user error, happy holidays! 😉

**Comment by kendallroth** [comment]
@the1killer Huge thanks for this tool; I am just starting out with Scrap Mechanic and wanted to get a good map location, but wasn't super happy with the ones I stumbled around in. Having this tool allowed me to generate a new world, copy the output, minify, replace in the HTML file, and refresh the webpage in about 15 seconds 😁. Huge thanks for your work and effort on this (and for graciously correcting my mixup)!

![amazing_seed_418188999](https://user-images.githubusercontent.com/12562420/147398726-00bf4175-db0a-4db6-b385-83a2bcd586c4.png)
